#!/bin/bash

FORMAT="${BLOCK_INSTANCE:-%H:%M}"
DATETIME=$(date "+${FORMAT}")


# Left click
if [[ "${BLOCK_BUTTON}" -eq 1 ]]; then
  zenity --calendar
fi

echo "${DATETIME}"
echo "${DATETIME}"
echo ""
